var express = require('express');
var router = express.Router();
var api_controller = require('../controllers/api');
var mobile_controller = require('../controllers/mobile');
router.get('/', api_controller.api);
router.post('/mobile', mobile_controller.mobile_create_post);
router.delete('/mobile/:id', mobile_controller.mobile_delete);
router.put('/mobile/:id', mobile_controller.mobile_update_put);
router.get('/mobile/:id', mobile_controller.mobile_detail);
router.get('/mobile', mobile_controller.mobile_list);
module.exports = router;
